# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='queueNo',
            new_name='queueNo',
        ),
    ]
