# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-20 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_overlapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='overlapping',
        ),
    ]
