# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180216_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_date',
            field=models.DateField(blank=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_time',
            field=models.TimeField(blank=True, verbose_name='Time'),
        ),
    ]
