# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180404_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
