# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20180409_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='overlapping',
            field=models.ManyToManyField(related_name='_booking_overlapping_+', to='booking.Booking'),
        ),
    ]
