# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(default='title', max_length=400),
        ),
    ]
