# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20180404_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(default='', max_length=400),
        ),
    ]
