# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20180404_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('gym ', 'GYM'), ('football field', 'FOOTBALL FIELD'), ('volleyball grounds', 'VOLLEYBALL GROUNDS')], default='gym', max_length=200),
        ),
    ]
