# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-06 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180430_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsgroup',
            name='active_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_board', to='groups.Board'),
        ),
    ]
